### ISSUE TITLE
Something That would be Majorly Helpful

### ISSUE THREAD

**Issue by christian-egglin** [learn-co-curriculum/sinatra-video-review-forms#1]
Something that I think would be incredibly helpful to add to these lecture videos, would be links right after the embedded video to the time in the video that the different important concepts/files are explained. Because, at least for me, when I watch these videos, sometimes towards the end when newer code we've written expands upon previous files or code, I like to go back to the explanation of the code as a refresher just so that I have fresh in my head how the old code functions when I'm looking at the new code. And without links it requires me to look through the video for when that is.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion. We will pass along the request to our educational team.

As always thank you for contributing.
