### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by ronsala** [learn-co-curriculum/sinatra-video-review-forms#10]
**Summary**

In this lecture, Avi discusses the differences and similarities between CLI apps and web apps, MVC, HTTP verbs, and how requests and responses are routed through the stack.

**Objectives**

- Use config.ru to start web apps using Rack
- Use Shotgun to spin up a server
- Explain MVC in relation to web apps
- Explain the uses of HTTP verbs for sending and receiving data
- Explain how languages, DSLs, frameworks, clients, and databases work together in a stack

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! 💙
