### ISSUE TITLE
Missing edit icon?

### ISSUE THREAD

**Issue by ronsala** [learn-co-curriculum/sinatra-video-review-forms#11]
The lesson instructions say, "You can also edit the lesson (find the paper and pen icon at the top right side of your lesson page) in Learn." I didn't find such an icon. Has it been removed?

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a fix to the Learn platform. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

You can reach the product team at support@learn.co. Alternatively, if Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.

Thanks! 💙
