### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by dmcgrann** [learn-co-curriculum/sinatra-video-review-forms#12]
Objectives:

1.	Learn how to build/onboard an application with CRUD functionality

2.	Describe REST and the request cycle

3.	Understand how Rack and Sinatra work

4.	Explain basic Sinatra MVC structure

Summary:

In this lecture, Avi walks through the development of basic web application using Sinatra. The lecture uses slides and coding walkthroughs to present students with a comprehensive overview of basic concepts. The emphasis is on Sinatra, but topics from many recent lessons are discussed. These include Rack, ORMs, CSS, and others.

It is very important that students have a thorough understanding of Sinatra before moving forward. You should feel free to watch this lecture as many times as necessary, and you are encouraged to search for additional resources using google or your favorite search engine.

Suggestions/Comments:

The recorded lectures have been an amazing resource for me. I see the utility of using them for review. This lecture works great to review recent topics. At other times, the lectures can be helpful to introduce a topic, or they can be useful in the middle of a section to help give background to especially complex topics. I would not have gotten through the object oriented ruby without recorded lectures. If anything, I’d favor making as many available as possible and as long as it makes sense.

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! 💙
