### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/sinatra-video-review-forms#2]
_Suggested Summary_
- In this lesson, we will be onboarded to a Sinatra application, discuss how to develop models, controllers and views in a Sinatra app and how they tie together, go over URL architecture, work through the Sinatra request cycle, and dive into creating Sinatra forms. 

_Suggested Objectives_
- Explain the concept of “onboarding” and why it’s best to start with the execution point.
- Discuss what purpose _controllers_ fill in our application and how to mount the various controllers we develop (and run one of them).
- Understand the different roles that _models_, _views_, and _controllers_ fill in the MVC structure of a web application.
- Use an instance variable in the controller action to provide information for the erb template.
- Know who came up with RESTful architecture and the various conventions of building a URL.
- Discuss the standard URLs you will want to build for each resource in your application.
- Build a route that utilizes a route variable.
- Explain what the _params_ hash is and what role it fills in web applications.
- Understand that a _query string_ is technically not part of the URL and why query strings can be detrimental to security.
- Discuss ActiveRecord’s involvement in Sinatra and Rails applications.
- Run through the Sinatra request cycle and understand why it is so important to internalize this process.
- Remember that every request happens in isolation (HTTP is a _stateless_ protocol).
- Use _<form>_ tags, along with the _action_ and _method_ properties, to build a simple Sinatra form.
- Remember that the order in which you define your routes matters.
- Use the _name_ property of a form to define where the data is going to end up in the _params_ hash.
- Define what _controls_ are, in the context of a form.
- Explain how the _name_ and _value_ properties of a form correspond to the _key_ and _value_ pairs of the _params_ hash.

**Comment by curiositypaths** [comment]
Thank you for sharing your Summary and Objectives.
