### ISSUE TITLE
The Pen And Paper Icon Has Been Removed

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/sinatra-video-review-forms#4]
This lab suggests offering edits by using the "paper and pen icon" at the top. 

"You can also edit the lesson (find the paper and pen icon at the top right side of your lesson page) in Learn. And once you click that you'll be able to add and submit your edits!"

A technical coach confirmed this feature seems to have been removed, so the README should be updated to reflect the correct methods for offering updates to the lessons.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a fix to the Learn platform. [Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

You can reach the product team at support@learn.co. Alternatively, if Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.

Thanks! 💙
