### ISSUE TITLE
Suggested summary

### ISSUE THREAD

**Issue by kriti-rai** [learn-co-curriculum/sinatra-video-review-forms#5]
**Summary**

For any rack-based Ruby web application, it is a good idea to start with peeping into config.ru file and getting the idea of the dependencies and the database. It might be a good idea to play around with the database a little bit just to get the sense of the schema and how each table maps to the models. Another important file to look at is the controller file which is tied with the models and the view. The MVC framework works similar to a chef-waiter-diner analogy. The waiter is the first person the diner talks to and tells them what they want. The waiter then takes up the request and passes it on to the chef who cooks up the food and gives it back to the waiter, who then presents it to the client. Similarly, a client, like a browser, makes a request to the model who then looks to the controller to return back the needed data which is then presented to the client. As controller is responsible for orchestrating the process of handling request and data, it is analogous to the brain of the framework. The way controller works with data is through routes which has two major components — action and view. The action a URL performs could be one of the CRUD — Create, Retrieve, Update, Destroy—actions, and aids in the choice of HTTP verb that defines the route. Part of the URL’s action is also rendering view which could be HTML, JSON, XML, etc.

**Comment by drakeltheryuujin** [comment]
Thanks for your feedback! 💙
