### ISSUE TITLE
Suggested Summary/Location

### ISSUE THREAD

**Issue by Awilmerding1** [learn-co-curriculum/sinatra-video-review-forms#6]
The video is labeled "Video Review: Forms" but  it is placed before the "Forms" section of the course.  I found the video fairly confusing since I do not yet know the basics of forms.  In particular, I am still confused about how to write a controller action so that the url will not have query strings.

Suggested Summary:

This video reviews the MVC framework, focusing mostly on the functions and structure of controllers.  The video begins by explaining how to mount a controller and then outlines the 7 controller actions that display and modify data.  Using a photo sharing website as an example, the video details how to set up a PostsController class that incorporates these 7 actions.  Route Variables, Query Strings, and the params hash are defined and demonstrated within this example.  The video then explains how to write an HTML form and then post that form to the website.

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! 💙
