### ISSUE TITLE
Suggested Summary

### ISSUE THREAD

**Issue by FionaDL** [learn-co-curriculum/sinatra-video-review-forms#7]
This video covers basic on-boarding; getting a general overview of what an application is doing, and how its flow works. It also goes more in depth on MVC, and touches briefly on the REST, created by Roy Fielding. We then go through the seven most common routes for viewing and creating content through an application; index, show, new, create, edit, update, and destroy.

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! 💙
