### ISSUE TITLE
Forms lecture

### ISSUE THREAD

**Issue by Pamela454** [learn-co-curriculum/sinatra-video-review-forms#9]
Could you please make the slides from the form lecture available? They look really helpful

**Comment by drakeltheryuujin** [comment]
Hi @Pamela454 ,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum.

For now, you can try reaching out to @aviflombaum and asking if he has a copy of the slides that can be made available, as we do not have access to these slides at this time.

Thanks! 💙
